### ISSUE TITLE
ability_building not leveled up

### ISSUE THREAD

**Issue by Septica** [MNoya/BuildingHelper#12]
I suspect that this was not intended. Seems like u forgot to level up `ability_building`. This make the `modifier_building` which gives magic immunity, root, deniability, low attack priority, and no collision not applied

**Comment by MNoya** [comment]
oops

Not even sure why I am not applying modifier_building directly. Will make a lua modifier for it and apply it directly (changing the detection of buildings to `unit:HasModifier("modifier_building")`)
