### ISSUE TITLE
Left and Right Clicks Bug - 1.2.0 update click.js

### ISSUE THREAD

**Issue by exotickg1** [MNoya/BuildingHelper#4]
After update all files i cant click on anything. Cant buy, cant use abilties, like my mouse is broken.
@MNoya  Any suggestions to fix it?

**Comment by exotickg1** [comment]
Forgot recompile (rebuild) sorry.

**Comment by exotickg1** [comment]
~~Forgot recompile (rebuild) sorry.~~
Rebuild (2x times) does not solve the problem :disappointed:

**Comment by MNoya** [comment]
[This is all that changed](https://github.com/MNoya/BuildingHelper/blob/9fbfc82246f6b6e4e81cbc4cfae32f37cdf50dd4/panorama/scripts/clicks.js)

Check for panorama errors in your console.

**Comment by exotickg1** [comment]
~~Of course i updated this js (1.2.0 downloaded again and did everything according to the instructions). No errors in console.~~
UPD: Sry, it was my problem with other script. Thanks for help
