### ISSUE TITLE
PlaceBuilding potential bug in buildinghelper.lua

### ISSUE THREAD

**Issue by TheOneZealot** [MNoya/BuildingHelper#5]
In buildinghelper.lua function PlaceBuilding, _newName_ is used though never declared (unless i'm missing something).

```
construction_size = construction_size or BuildingHelper:GetConstructionSize(newName)
pathing_size = pathing_size or BuildingHelper:GetBlockPathingSize(newName)
```

If i'm not mistaken this should be

```
construction_size = construction_size or BuildingHelper:GetConstructionSize(name)
pathing_size = pathing_size or BuildingHelper:GetBlockPathingSize(name)
```

since _name_ is passed as an argument.

**Comment by MNoya** [comment]
Correct, badly copied. Those are the fallbacks in case the function is called like `PlaceBuilding(player, name, location)`, will fix
