### ISSUE TITLE
Allow trees to be regrown

### ISSUE THREAD

**Issue by Septica** [MNoya/BuildingHelper#6]
Since buildinghelper.lua leaves an npc thinker unit on a fallen tree. It blocks the regrowth of the tree. It would be nice to have some way to detect a tree regrowth and destroy the associated npc thinker.

**Comment by MNoya** [comment]
As there is no tree regrow event, there are 4 default API functions it should need to hook to make this transparent:
- `GameRules:SetTreeRegrowTime(time)` (Default: 300 seconds)
- `GridNav:RegrowAllTrees()`
- `tree:CutDownRegrowAfter(time, team)`
- `tree:GrowBack(time)`

**Comment by MNoya** [comment]
Done, give it a try and post again if there's any problem
