### ISSUE TITLE
Building's HP was off

### ISSUE THREAD

**Issue by Septica** [MNoya/BuildingHelper#7]
I tried this with my building HP = 500, build time from 1 second to 9 seconds. The building's HP was off when the build time is 3, 6, or 7. Seems like it doesn't work well when HP divided by build time is a number that goes infinitely. It also doesn't work well with floating point number like 0.5 and 2.5.

**Comment by MNoya** [comment]
With 500 HP and 3 seconds I got `[BH] Finished orc_barracks in 2 seconds. HP was off by -5` effectively, I'll investigate.
